🚧 Update to SDK 27.25.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🤾🏻🧑🏽‍🦲💁🏻‍♂️🙅🏻‍♀️

Full error log:
Error:  asset 2022-9-3--3-11-10--68c393ba-ec25-4f98-b971-0ef9004b78ad/main.min.js 1.25 MiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 1.24 MiB
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 85 KiB [built] [code generated]
./node_modules/heic2any/dist/heic2any.js 1.16 MiB [built] [code generated]
./src/heic-import.module.tsx 4.44 KiB [built] [code generated] [1 error]
./package.json 710 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx
./src/heic-import.module.tsx 2:4-17
[tsl] ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx(2,5)
TS2724: '"@collboard/modules-sdk"' has no exported member named 'blobToDataUrl'. Did you mean 'blobToDataurl'?

webpack 5.35.1 compiled with 1 error in 5757 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\heif-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\heif-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\heif-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\heif-support\node_modules\webpack\lib\Watching.js:201:28)