🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🇧🇴🙏🏻⚀🔻

Full error log:
Error:  asset 2022-7-25--0-30-3--1722e9c4-fb92-4971-adf1-c61891196deb/main.min.js 1.22 MiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 1.21 MiB
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 54.7 KiB [built] [code generated]
./node_modules/heic2any/dist/heic2any.js 1.16 MiB [built] [code generated]
./src/heic-import.module.tsx 4.41 KiB [built] [code generated] [3 errors]
./package.json 711 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx
./src/heic-import.module.tsx 73:99-104
[tsl] ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx(73,100)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.

ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx
./src/heic-import.module.tsx 74:44-54
[tsl] ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx(74,45)
TS2339: Property 'windowSize' does not exist on type 'AppState'.

ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx
./src/heic-import.module.tsx 74:81-86
[tsl] ERROR in C:\Users\me\work\collboard\heif-support\src\heic-import.module.tsx(74,82)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.

webpack 5.35.1 compiled with 3 errors in 6842 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\heif-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\heif-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\heif-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\heif-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\heif-support\node_modules\webpack\lib\Watching.js:201:28)